This package is a very basic, python 3 [[tureng.com]] wrapper of thier mobile api. Please read the [[https://tureng.com/en/termsofuse][terms and conditions]] of the tureng before the use this package on any production.

* Useage
~Tureng.translate(word:str)~ method returns a ~TranslatedResult~ object. It has meta data like ~is_turkish~ or ~is_found~ and the translated words on ~grouped_results~ or ~common_useages~. If the translation can't found it will suggest list of string on ~suggestions~.

~grouped_results~ is a dictinoary. Keys are group name of the translation (like 'Common Usage' or "Computer Engineering Term"..) and the values are list of TurEngWord. 

~TurEngWord~ is just a class that store the translation strings and group_name (like is it 'Common Usage' translation or 'Medical Term' translation).

Example useage:
#+BEGIN_SRC python
  from tureng import TurEng

  tureng = TurEng()

  yes = tureng.translate("yes")

  yes.most_common_translation # 'evet'
  yes.has_error               # False
  yes.is_found                # True
  yes.is_english              # True
  yes.is_turkish              # False
  yes.searched_term           # 'yes'
  yes.grouped_results         # {'group_name': [TurEngWord, TurEngWord....], .............}
  yes.suggestions             # None
  yes.common_useages          # [TurEngWord, TurenWord, .....]

  # TurEngWord class
  word_evet = yes.common_useages[0] # most most_common_translation, we could 
                                     # write t_yes.most_common_translation

  word_evet.tr                                             # 'evet'
  word_evet.eng                                            # 'yes'
  word_evet.group_eng                                      # 'Common Usage (en->tr)'
  t_yes.common_useages[0] == t_yes.most_common_translation # True


  # Turkish search
  t_evet = tureng.translate("evet")
  t_evet.is_turkish      # True


  # None found search
  t_yys = tureng.translate("yys")
  t_yys.is_found      # False
  t_yys.suggestions  # ['yrs', 'yas', 'yds', 'ygs', 'dys', 'yes', 'öys', 'days', 'brys', 'yoyo']
#+END_SRC

* Tests
Please note that this package is an unofficial wrapper. So if the tureng API will change, the package will not work. Maybe you want to check is it run properley.

#+BEGIN_SRC bash
  python tureng/tests.py
#+END_SRC


* Thanks
Thanks to [[https://github.com/yozel/tureng]] yozel for the his open-source code which inspires to write this. 
